name: Checks

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Run Golang Lint Command
        run: |
          make lint

  copyright:
    runs-on: ubuntu-latest
    name: Copyrights

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          config: .licenserc.yaml